// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using RaysHotDogs.Core.Model;
using RaysHotDogs.Core.Service;
using RAysHotDogs.DataSources;
using UIKit;

namespace RAysHotDogs
{
    public partial class FavoriteTableViewController : BaseTableCategory
	{
        public FavoriteTableViewController (IntPtr handle) : base (handle)
		{
		}
        HotDogDetailServices dataService = new HotDogDetailServices();

        public async override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var favoritesHotDog = dataService.GetFavoriteHotDogs();
            var datasource = new HotDogDataSources<FavoriteTableViewController>(favoritesHotDog, this);
            TableView.Source = datasource;

            this.NavigationItem.Title = "RAy's FAvorite";


        }

        public override async void HotDogSelected(HotDog selectedHotDog)
        {
            HotDogDetailViewController hotDogDetailViewController = this.Storyboard.InstantiateViewController("hotDogDetailViewController") as HotDogDetailViewController;

            if (hotDogDetailViewController != null)
            {
                hotDogDetailViewController.ModalTransitionStyle = UIModalTransitionStyle.PartialCurl;
                hotDogDetailViewController.SelectedHotDog = selectedHotDog;
                await PresentViewControllerAsync(hotDogDetailViewController, true);
            }
        }
	}
}
