// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using RaysHotDogs.Core.Service;
using RAysHotDogs.DataSources;
using UIKit;

namespace RAysHotDogs
{
	public partial class HotDogTableViewController : UITableViewController
	{

        HotDogDetailServices dataService = new HotDogDetailServices();


		public HotDogTableViewController (IntPtr handle) : base (handle)
		{
		}


        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            var hotDogs = dataService.GetAllHotDogs();
            var datasource = new HotDogDataSources(hotDogs, this);
            TableView.Source = datasource;
        }




    }
}
