// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace RAysHotDogs
{
	public partial class HotDogDetailSegue : UIStoryboardSegue
	{
		public HotDogDetailSegue (IntPtr handle) : base (handle)
		{
		}
	}
}
